INSERT INTO projects (title, description, full_description, technologies, status, type, github_url, gradient, challenges, learned, timeline, is_featured) VALUES
('KFT-WEBPAGE', 'Production-ready personal portfolio website with CMS support using Supabase.', 'Production-ready personal portfolio website with CMS support using Supabase.', ARRAY['Next.js', 'Tailwind CSS', 'TypeScript', 'Supabase', 'Framer Motion', 'Shadcn/UI'], 'completed', 'Web Application', 'https://github.com/YUET-944/KFT-WEBPAGE', 'from-blue-500 to-purple-600', ARRAY['CMS Integration', 'Performance Optimization'], ARRAY['Supabase Auth', 'Server Components'], '6 months', TRUE),
('MYK-WEBPAGE', 'Initial version of portfolio webpage with basic layout and UI components.', 'Initial version of portfolio webpage with basic layout and UI components.', ARRAY['HTML', 'CSS', 'JavaScript'], 'completed', 'Web Application', 'https://github.com/YUET-944/MYK-WEBPAGE', 'from-green-500 to-teal-600', ARRAY['Responsive Design'], ARRAY['Basic Web Development'], '2 months', FALSE),
('STUDENT-ADMISSION-SYSTEM', 'Student record and admission management system developed in C.', 'Student record and admission management system developed in C.', ARRAY['C', 'File Handling', 'Structs'], 'completed', 'Desktop Application', 'https://github.com/YUET-944/STUDENT-ADMISSION-SYSTEM', 'from-red-500 to-orange-600', ARRAY['Data Persistence'], ARRAY['C Programming', 'File I/O'], '3 months', FALSE),
('ATM-System', 'OOP-based ATM simulation project with deposit, withdraw, and balance operations.', 'OOP-based ATM simulation project with deposit, withdraw, and balance operations.', ARRAY['C++', 'File Handling', 'OOP'], 'completed', 'Desktop Application', 'https://github.com/YUET-944/ATM-System', 'from-purple-500 to-pink-600', ARRAY['Object-Oriented Design'], ARRAY['C++ OOP', 'Error Handling'], '2 months', FALSE),
('DSA-tollkit', 'A toolkit of DSA problems including sliding window and linked list implementations.', 'A toolkit of DSA problems including sliding window and linked list implementations.', ARRAY['C++', 'Data Structures', 'Algorithms'], 'completed', 'Algorithm', 'https://github.com/YUET-944/DSA-tollkit', 'from-yellow-500 to-orange-600', ARRAY['Algorithmic Efficiency'], ARRAY['DSA Concepts'], '4 months', FALSE),
('job-portal', 'A backend project focused on job listing and applicant management using SQL.', 'A backend project focused on job listing and applicant management using SQL.', ARRAY['MySQL', 'PHP', 'HTML/CSS'], 'completed', 'Web Application', 'https://github.com/YUET-944/job-portal', 'from-gray-700 to-gray-900', ARRAY['Database Normalization'], ARRAY['Backend Development', 'SQL Queries'], '5 months', FALSE),
('pharmacy-ui-ux-design', 'UI/UX design prototype for a pharmacy management application.', 'UI/UX design prototype for a pharmacy management application.', ARRAY['Figma', 'UI/UX Principles'], 'completed', 'Design', 'https://github.com/YUET-944/pharmacy-ui-ux-design', 'from-indigo-500 to-purple-700', ARRAY['User Research'], ARRAY['Figma Prototyping', 'UX Principles'], '1 month', FALSE),
('UI-UX-DESIGN', 'Portfolio of various UI/UX design works and prototypes.', 'Portfolio of various UI/UX design works and prototypes.', ARRAY['Figma', 'Adobe XD'], 'completed', 'Design', 'https://github.com/YUET-944/UI-UX-DESIGN', 'from-cyan-500 to-blue-700', ARRAY['Design System Creation'], ARRAY['UI/UX Tools'], '3 months', FALSE),
('BOT', 'Initial setup of a machine learning and deep learning-based trading prediction bot.', 'Initial setup of a machine learning and deep learning-based trading prediction bot.', ARRAY['Python', 'ML', 'DL', 'BeautifulSoup', 'TensorFlow'], 'completed', 'AI/ML Project', 'https://github.com/YUET-944/BOT', 'from-orange-400 to-red-600', ARRAY['Data Collection', 'Model Training'], ARRAY['Machine Learning', 'Deep Learning'], '6 months', FALSE),
('EID-GREEDING', 'A simple Eid greeting webpage with animations.', 'A simple Eid greeting webpage with animations.', ARRAY['HTML', 'CSS', 'JavaScript'], 'completed', 'Web Application', 'https://github.com/YUET-944/EID-GREEDING', 'from-pink-500 to-red-700', ARRAY['CSS Animations'], ARRAY['Frontend Basics'], '1 week', FALSE);
